- package-lock.json
- src/commands/open-my-home-page.ts
- src/commands/post-category/delete-selected-categoriess.ts
- src/models/user-settings.ts
> fix: use space-user-id to build user home page url

- src/commands/upload-image/upload-local-disk-image.ts
> fix(upload-local-disk-image): support select gif file

- package.json
> fix: fix context menu of category list

- package-lock.json
- package.json
- src/commands/posts-list/open-post-in-vscode.ts
- src/commands/posts-list/save-post.ts
- src/services/post-title-sanitizer.service.ts
fix #28 
打开远程博文到本地时会进行`sanitize`操作，本地保存到远程时对标题进行`unsanitize`
`unsanitize`时如果发现用户对本地文件的标题进行了修改，那么下次保存到远程时会使用修改后的标题，否则会使用`unsanitize`出来的标题
> fix(#28): fix unable to open the remote post if post title containes invalid symbol

- README.md
- package.json
- src/commands/posts-list/save-post.ts
> feat(#37):  allow use vscode-cnb.save-post-file-to-cnblogs with command palette

- package.json
- src/assets/icon-upload-dark.svg
- src/commands/commands-registration.ts
> fix(editor-title): fix image upload action not work on editor title

- src/extension.ts
- src/services/edit-post-uri-handler.ts
e.g. `vscode://cnblogs.vscode-cnb/edit-post/<postId>`
> feat: add uri handler used to open a existing post

- src/commands/posts-list/rename-post.ts
See [InputBoxOptions](https://code.visualstudio.com/api/references/vscode-api#InputBoxOptions) for this option.
> Add a default value for rename input box

- package.json
- src/commands/view-post-online.ts
> ui: make view-post-online command visible in vscode command palette

- src/services/post-configuration-panel.service.ts
> fix(#53): fix post configuration panel stuck in the loading ui with vscode 1.67

- ui/post-configuration/components/PostEntryNameInput.tsx
- ui/post-configuration/components/PostForm.tsx
> feat(post-configuration-panel): allow input entry name of the post

- src/commands/posts-list/open-post-in-vscode.ts
> fix(create-local-post-file-with-category): sanitize name of the category

- README.md
- package.json
- src/commands/command-handler.ts
- src/commands/commands-registration.ts
- src/commands/posts-list/copy-link.ts
- src/commands/posts-list/modify-post-settings.ts
- src/commands/pull-post-remote-updates.ts
- src/commands/view-post-online.ts
- src/models/post.ts
- src/services/alert.service.ts
> feat: copy link of a post

- src/commands/extract-images.ts
- src/services/images-extractor.service.ts
Details of improvements for resolving image file:
- Try decode the file path if not found
- Try resolve the image file in current workspace folders if not found
> feat(image-extract): improvements for image file resolving

- .eslintrc.json
- .github/workflows/build-check.yml
- .vscode/launch.json
- .vscode/settings.json
- .vscode/tasks.json
- __mocks__/vscode.ts
- package-lock.json
- package.json
- src/services/images-extractor.service.ts
- src/services/post.service.ts
- src/services/settings.service.test.ts
- src/services/settings.service.ts
- src/test/runTest.ts
- src/test/suite/extension.test.ts
- src/test/suite/index.ts
- src/utils/untildify.test.ts
- src/utils/untildify.ts
- test/jest.config.mjs
- test/jest.config.ts
- test/tsconfig.json
- tsconfig.integration.json
- tsconfig.json
- tsconfig.spec.json
- webpack.config.mjs
- unit test with jest
- use different workspace uri configuration on different os
> fix: use respective workspace uri on different platforms

- src/authentication/account-manager.ts
- src/authentication/authentication-provider.ts
> fix(login): force new session when login

- src/models/post.ts
- src/tree-view-providers/models/post-metadata.ts
- ui/post-configuration/components/AccessPermissionSelector.tsx
- ui/post-configuration/components/PostForm.tsx
> ui(post-list): enrich post metadata

- src/commands/pdf/post-pdf-template-builder.ts
- src/commands/post-category/new-post-category.ts
- src/commands/posts-list/open-post-in-vscode.ts
- src/commands/show-local-file-to-post-info.ts
- src/models/post-category.ts
- src/models/webview-commands.ts
- src/services/post-category.service.ts
- src/services/post-configuration-panel.service.ts
- src/tree-view-providers/models/post-category-tree-item.ts
- src/tree-view-providers/models/post-metadata.ts
- src/tree-view-providers/post-categories-tree-data-provider.ts
- src/utils/input-post-settings.ts
- ui/global.d.ts
- ui/post-configuration/App.tsx
- ui/post-configuration/components/CategoriesSelect.tsx
- ui/post-configuration/components/ErrorResponse.tsx
- ui/post-configuration/components/NestCategoriesSelect.tsx
- ui/post-configuration/components/PostForm.tsx
- ui/post-configuration/services/personal-categories-store.ts
- ui/tsconfig.json
> feat: add support for nest categories

- ui/post-configuration/components/AccessPermissionSelector.tsx
> fix(post-configuration): fix unable to select only-myself

- src/services/images-extractor.service.ts
> fix: fix image match regex

- src/cmd/post-list/post-list-view.ts
- src/tree-view/provider/post-data-provider.ts
> fix: empty post lists

- src/cmd/post-list/post-list-view.ts
- src/service/post/post-list-view.ts
- src/tree-view/provider/post-data-provider.ts
> fix: 'State is undefined'

- src/service/post/post-list-view.ts
> fix:  suppress view reveal exception

- rs/Cargo.lock
- rs/Cargo.toml
- rs/src/cnb/ing/mod.rs
- rs/src/cnb/ing/publish.rs
> fix: ing client type

- src/service/post/post-cfg-panel.ts
> fix: webview is disposed

- src/service/post/post-cfg-panel.ts
> fix: 'webview is disposed'

- src/cmd/post-list/upload-post.ts
> fix: upload post not working

- ui/post-cfg/components/select/CatSelect.tsx
> fix: unable to unselect category

- src/auth/auth-manager.ts
- src/auth/auth-provider.ts
> fix: pat authentication

- src/cmd/post-list/post-pull.ts
> fix: file path check for post-pull

- src/cmd/upload-img/upload-fs-img.ts
> fix: image file path

- src/service/post/post-file-map.ts
Reverts cnblogs/vscode-cnb#233
> Revert "fix: refresh category list when pulling post"

- src/service/extract-img/find-img-link.ts
> fix: html image tag regex

- src/service/extract-img/find-img-link.ts
- src/service/extract-img/get-replace-list.ts
> feat: extract image without extension

- src/cmd/post-list/post-pull.ts
- src/service/post/post-file-map.ts
> fix: check workspace path when get file path

- ui/tsconfig.json
- ui/webpack.config.mjs
- webpack.config.mjs
Reverts cnblogs/vscode-cnb#258
> Revert "chore: fix compile markdown.entry.ts"

- package-lock.json
- package.json
- src/ctx/cfg/markdown.ts
- src/markdown/extend-markdownIt.ts
> feat(markdown): support image sizing syntax

- src/service/extract-img/find-img-link.ts
Reverts cnblogs/vscode-cnb#264
> Revert "refactor(markdown): improve image mark match regex"

- package.json
Fix https://github.com/cnblogs/vscode-cnb/issues/165#issuecomment-1839905261
> fix: typos

- src/service/extract-img/find-img-link.ts
> refactor: replace rust regex for markdown images

- src/ctx/cfg/workspace.ts
- src/service/post/post-file-map.ts
> feat: update post-file map for changed workspace

- src/service/extract-img/find-img-link.ts
> fix: regex for matching markdown images

- src/service/post/post-file-map.ts
> fix: path replacement

- src/auth/auth-manager.ts
- src/infra/alert.ts
- src/service/user.service.ts
> fix: command not found

- src/cmd/post-list/modify-post-setting.ts
- src/cmd/post-list/upload-post.ts
- src/service/extract-img/extract-img.ts
> fix: auto extract images

- src/service/post/create.ts
> fix: set displayOnHomePage to true

- src/service/code-challenge.ts
> fix: remove unused code to work with vscode 1.90

- .eslintrc.json
- src/cmd/upload-img/upload-img-from-path.ts
- src/cmd/upload-img/upload-img.ts
- src/service/upload-img/image.service.ts
> fix: revert upload-img changes
